# Generated by Django 5.1 on 2024-09-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TramRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('tram_number', models.CharField(max_length=10)),
                ('direction', models.CharField(max_length=100)),
                ('schedule', models.TextField()),
            ],
        ),
    ]
